version: "3.9"

services:
  vinhoodapp:
    container_name: BUY_ME_A_GIFT
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=buy_me_a_gift_vinhood
      - DB_USER=postgres
      - DB_PASS=root
      - DB_HOST=db
      - DB_PORT=5432
      - EMAIL_HOST=sandbox.smtp.mailtrap.io
      - EMAIL_PORT=2525
      - EMAIL_HOST_USER=0092622d3590ee
      - EMAIL_HOST_PASSWORD=1da748785a6027
      - DJANGO_SECRET_KEY=django-insecure-zb%6isg5em7k_aj1&fcl)fwalfin@ym$4w@9v=!f&+qnqmp7ep
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:15
    environment:
      - POSTGRES_DB=buy_me_a_gift_vinhood
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}
