# Generated by Django 4.1.7 on 2023-03-31 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WishList',
        ),
    ]
