import Head from "next/head";
import Image from "next/image";
import { Hubballi, Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useEffect, useState } from "react";
import { getProducts } from "@/utils/api";
import { CardContent } from "@mui/material";
import Typography from "@mui/material/Typography";
import CardActions from "@mui/material/CardActions";
import Button from "@mui/material/Button";
import Card from "@mui/material/Card";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [products, setProducts] = useState([]);

  useEffect(() => {
    (async () => {
      const data = await getProducts();
      setProducts(data);
    })();
  }, []);
  const toReadableDate = (dateString: string) => {
    const date = new Date(dateString);
    const options = { year: "numeric", month: "short", day: "numeric" };
    const formatter = new Intl.DateTimeFormat("en-US", options);
    const formattedDate = formatter.format(date);
    return formattedDate;
  };
  const addToWishList = (product_id: number) => {};

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <nav className={styles.navbar}>
          <h1>
            <b>BUY ME A GIFT</b> powerd by vinhood
          </h1>
          <div className={styles.auth}>
            <div>
              <a href="/login">Login</a>
            </div>
            <div>
              <a href="/signup">Register</a>
            </div>
          </div>
        </nav>
        <div className={styles.container}>
          <h1 className={styles.title}>
            <b>Products</b>
          </h1>
          <div className={styles.productsContainer}>
            {products.map(
              (
                product: {
                  id: number;
                  name: string;
                  price: number;
                  created_time: string;
                  product_category: { name: string };
                },
                index
              ) => (
                <Card key={index}>
                  <CardContent>
                    <Typography
                      sx={{ fontSize: 14 }}
                      color="text.secondary"
                      gutterBottom
                    >
                      Product Name
                    </Typography>
                    <Typography variant="h5" component="div">
                      {product.name}
                    </Typography>
                    <Typography sx={{ mb: 1.5 }}>
                      Price {product.price} ETB
                    </Typography>
                    <Typography variant="body2">
                      Created at {toReadableDate(product.created_time)}
                    </Typography>
                  </CardContent>
                  <CardActions>
                    <Button size="small" onClick={addToWishList(product.id)}>
                      Add to WishList
                    </Button>
                  </CardActions>
                </Card>
              )
            )}
          </div>
        </div>
      </main>
    </>
  );
}
